
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-node-app
  template:
    metadata:
      labels:
        app: cicd-node-app
    spec:
      containers:
      - name: app
        image: rubi58/CICD-Pipeline-with-GitHub-Actions-Docker:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-node-service
spec:
  type: NodePort
  selector:
    app: cicd-node-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
